---
- hosts: printservers
  user: root
  vars_files:
    - vars/printers.yml
  
#  tasks:
#    - name: copy CUPS filter to server
#      copy:
#        src: pstokdk
#        dest: /usr/local/bin/pstokdk
#        owner: root
#        group: wheel
#        mode: 755

- name: Receipt printers
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/printers.yml

  tasks:
    - name: format receipt printer queue names
      format_lists:
        format_spec: '%sReceipt-%s'
        lists:
          - "{{ printers }}"
          - "{{ receipt_forms }}"
      register: receipt_queues

    - name: format reminder printer queue names
      format_lists:
        format_spec: '%sReminder-%s'
        lists:
          - "{{ printers }}"
          - "{{ reminder_forms }}"
      register: reminder_queues

    - name: format giving report printer queue names
      format_lists:
        format_spec: '%s-Give-%sPage'
        lists:
          - "{{ printers }}"
          - "{{ give_forms }}"
      register: give_queues

    - name: format pdf report printer queue names
      format_lists:
        format_spec: '%s-%s'
        lists:
          - "{{ printers }}"
          - "{{ pdf_forms }}"
      register: pdf_queues

    - debug: var=receipt_queues
    - debug: var=reminder_queues
    - debug: var=give_queues
    - debug: var=pdf_queues
