---
- hosts: printservers
  user: root
  vars_files:
    - vars/printers.yml
  
  tasks:
    - name: copy CUPS filter to server
      copy:
        src: pstokdk
        dest: /usr/local/bin/pstokdk
        owner: root
        group: wheel
        mode: 755
