#!/usr/bin/perl

if ($#ARGV != 0) {
	print "need 1 and only 1 arg, sorry!\n";
	exit;
}
$PAGES=$ARGV[0];
$PAGES =~ s/.*-Give-//;
if (! ($PAGES =~ /^(\d+)$/)) {
	print "arg is not numeric: $ARGV[0]\n";
	exit;
}
if ($PAGES <= 0) {
	print "arg must be > 0: $ARGV[0]\n";
	exit;
}
$hdr = "%%+                    ";
$line=$hdr;
for ($count = 1; $count <= 3000; $count += $PAGES) {
	$line .= " $count";
	if (length($line) > 75) {
		print "$line\n";
		$line=$hdr;
	}
}
print "$line\n" if length($line) > length($hdr);
